version: '3.8'

services:
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    volumes:
    - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env